### ISSUE TITLE
Game crashing on Start

### ISSUE THREAD

**Issue by daniell0999** [Sinytra/ForgifiedFabricAPI#120]
### Describe the bug

Once i start the game it shows the red minecraft screen for a second and then crashes with no context. It is the api since it was the only mod i added to the mod folder. I tried this on multiple versions of the mod.

### Steps to reproduce

1.Start Game
2.Red title screen shows (no text, just red)
3.Game crashes
...

### Logs

[19:22:26] [main/INFO]: ModLauncher running: args [--username, AGDaniel09, --version, forge-48.1.0, --gameDir, C:\Users\patma\curseforge\minecraft\Instances\forge creation, --assetsDir, C:\Users\patma\curseforge\minecraft\Install\assets, --assetIndex, 8, --uuid, 8794257cc5a44a44bb13248d1831c710, --accessToken, ????????, --clientId, NTM5MTFiMjUtYmE4NC00NGViLWFmODEtYjYyMjE4YjcwZWJm, --xuid, 2535410175291044, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\patma\curseforge\minecraft\Install\quickPlay\java\1714238542968.json, --launchTarget, forge_client, --fml.forgeVersion, 48.1.0, --fml.mcVersion, 1.20.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230921.100330] [19:22:26] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 17.0.8+7-LTS [19:22:26] [main/INFO]: ModLauncher 10.1.1 starting: java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0 [19:22:26] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow [19:22:26] [main/INFO]: Trying GL version 4.6 [19:22:26] [main/INFO]: Requested GL version 4.6 got version 4.6 [19:22:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/patma/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT [19:22:27] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 552.22, NVIDIA Corporation [19:22:27] [main/INFO]: Found mod file fabric-api-0.92.1+1.11.8+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\patma\curseforge\minecraft\Instances\forge creation\mods} [19:22:27] [main/WARN]: Mod file C:\Users\patma\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.20.2-48.1.0\fmlcore-1.20.2-48.1.0.jar is missing mods.toml file [19:22:27] [main/WARN]: Mod file C:\Users\patma\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.20.2-48.1.0\javafmllanguage-1.20.2-48.1.0.jar is missing mods.toml file [19:22:27] [main/WARN]: Mod file C:\Users\patma\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.20.2-48.1.0\lowcodelanguage-1.20.2-48.1.0.jar is missing mods.toml file [19:22:27] [main/WARN]: Mod file C:\Users\patma\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.20.2-48.1.0\mclanguage-1.20.2-48.1.0.jar is missing mods.toml file [19:22:27] [main/INFO]: Found mod file fmlcore-1.20.2-48.1.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:27] [main/INFO]: Found mod file javafmllanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:27] [main/INFO]: Found mod file lowcodelanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:27] [main/INFO]: Found mod file mclanguage-1.20.2-48.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:27] [main/INFO]: Found mod file client-1.20.2-20230921.100330-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:27] [main/INFO]: Found mod file forge-1.20.2-48.1.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6c37bd27 [19:22:28] [main/INFO]: Found 46 dependencies adding them to mods collection [19:22:28] [main/INFO]: Found mod file fabric-dimensions-v1-2.1.54+8005d10d77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-transfer-api-v1-3.3.5+631c9cd677.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-game-rule-api-v1-1.0.40+683d4da877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-renderer-api-v1-3.2.1+1d29b44577.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-api-base-0.4.31+ef105b4977.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-api-lookup-api-v1-1.6.36+67f9824077.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-model-loading-api-v1-1.0.3+6274ab9d77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-item-api-v1-2.1.28+4d0bbcfa77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-block-api-v1-1.0.11+0e6cb7f777.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-resource-conditions-api-v1-2.3.8+9ad825cd77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-screen-handler-api-v1-1.3.30+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-models-v0-0.4.2+7c3892a477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-resource-loader-v0-0.11.10+bcd08ed377.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-rendering-v1-3.0.8+66e9a48f77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-renderer-indigo-1.5.1+67f9824077.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-item-group-api-v1-4.0.12+c9161c2d77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-loader-2.6.0+0.15.0+1.20.1-full.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-command-api-v1-1.2.34+f71b366f77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-mining-level-api-v1-2.1.50+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-block-view-api-v2-1.0.1+0767707077.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-command-api-v2-2.2.13+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-biome-api-v1-13.0.13+dc36698e77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file mixinextras-forge-0.3.5.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-entity-events-v1-1.6.0+6274ab9d77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-registry-sync-v0-2.3.3+1c0ea72177.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-recipe-api-v1-1.0.21+514a076577.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-loot-api-v2-1.2.1+eb28f93e77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-object-builder-api-v1-11.1.3+2174fc8477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-screen-api-v1-2.0.8+45a670a577.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-rendering-data-attachment-v1-0.3.37+a6081afc77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-networking-api-v1-1.3.11+503a202477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-sound-api-v1-1.0.13+4f23bd8477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-particles-v1-1.1.2+78e1ecb877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file MixinExtras-0.3.5.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-message-api-v1-5.1.9+52cc178c77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-content-registries-v0-4.0.11+a670df1e77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-transitive-access-wideners-v1-4.3.1+1880499877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-lifecycle-events-v1-2.2.22+afab492177.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-data-generation-api-v1-12.3.4+369cb3a477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-key-binding-api-v1-1.0.37+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:28] [main/INFO]: Found mod file fabric-client-tags-api-v1-1.1.2+5d6761b877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@7a34f66a [19:22:30] [main/INFO]: Compatibility level set to JAVA_17 [19:22:30] [main/ERROR]: Mixin config fabric-item-api-v1.client.mixins.json does not specify "minVersion" property [19:22:30] [main/ERROR]: Mixin config fabric-item-group-api-v1.mixins.json does not specify "minVersion" property [19:22:30] [main/ERROR]: Mixin config fabric-item-group-api-v1.client.mixins.json does not specify "minVersion" property [19:22:30] [main/ERROR]: Mixin config fabric-data-attachment-api-v1.mixins.json does not specify "minVersion" property [19:22:30] [main/ERROR]: Mixin config fabric-data-attachment-api-v1.client.mixins.json does not specify "minVersion" property [19:22:30] [main/INFO]: Propagating FML mod list to Fabric Loader [19:22:30] [main/INFO]: Launching target 'forge_client' with arguments [--version, forge-48.1.0, --gameDir, C:\Users\patma\curseforge\minecraft\Instances\forge creation, --assetsDir, C:\Users\patma\curseforge\minecraft\Install\assets, --uuid, 8794257cc5a44a44bb13248d1831c710, --username, AGDaniel09, --assetIndex, 8, --accessToken, ????????, --clientId, NTM5MTFiMjUtYmE4NC00NGViLWFmODEtYjYyMjE4YjcwZWJm, --xuid, 2535410175291044, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, C:\Users\patma\curseforge\minecraft\Install\quickPlay\java\1714238542968.json] [19:22:30] [main/WARN]: Error loading class: net/minecraftforge/network/NetworkHooks (java.lang.ClassNotFoundException: net.minecraftforge.network.NetworkHooks) [19:22:30] [main/WARN]: @Mixin target net.minecraftforge.network.NetworkHooks was not found fabric-screen-handler-api-v1.mixins.json:NetworkHooksMixin [19:22:30] [main/WARN]: Error loading class: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk$RebuildTask (java.lang.ClassNotFoundException: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask) [19:22:30] [main/WARN]: @Mixin target net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask was not found fabric-renderer-indigo.mixins.json:ChunkBuilderBuiltChunkRebuildTaskMixin [19:22:30] [main/WARN]: Error loading class: net/minecraft/network/protocol/game/ServerboundCustomPayloadPacket (java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket) [19:22:30] [main/WARN]: @Mixin target net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket was not found fabric-networking-api-v1.mixins.json:accessor.CustomPayloadC2SPacketAccessor [19:22:30] [main/WARN]: Error loading class: net/minecraft/network/protocol/login/ServerboundCustomQueryPacket (java.lang.ClassNotFoundException: net.minecraft.network.protocol.login.ServerboundCustomQueryPacket) [19:22:30] [main/WARN]: @Mixin target net.minecraft.network.protocol.login.ServerboundCustomQueryPacket was not found fabric-networking-api-v1.mixins.json:accessor.LoginQueryResponseC2SPacketAccessor [19:22:30] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). [19:22:30] [main/FATAL]: Mixin apply failed fabric-screen-api-v1.mixins.json:MinecraftClientMixin -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on beforeScreenTick could not find any targets matching 'm_231445_' or 'Lnet/minecraft/client/Minecraft;lambda$tick$42()V' in net.minecraft.client.Minecraft. Using refmap fabric-screen-api-v1-refmap.json [PREINJECT Applicator Phase -> fabric-screen-api-v1.mixins.json:MinecraftClientMixin -> Prepare Injections ->  -> handler$zff000$beforeScreenTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeScreenTick could not find any targets matching 'm_231445_' or 'Lnet/minecraft/client/Minecraft;lambda$tick$42()V' in net.minecraft.client.Minecraft. Using refmap fabric-screen-api-v1-refmap.json [PREINJECT Applicator Phase -> fabric-screen-api-v1.mixins.json:MinecraftClientMixin -> Prepare Injections ->  -> handler$zff000$beforeScreenTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.1.jar:10.1.1] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37) ~[modlauncher-10.1.1.jar:?] 	at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:418) ~[securemodules-2.2.3.jar:?] 	at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367) ~[securemodules-2.2.3.jar:?] 	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383) ~[securemodules-2.2.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] 	at java.lang.Class.privateGetPublicMethods(Class.java:3433) ~[?:?] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] 	at net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:599) ~[fmlearlydisplay-1.20.2-48.1.0.jar:1.0] 	at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.2-48.1.0.jar:1.0] 	at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.2-48.1.0.jar:1.0] 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:77) ~[fmlloader-1.20.2-48.1.0.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?] 	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?]

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
