### ISSUE TITLE
Incompatible with modern forwarding

### ISSUE THREAD

**Issue by CollinToGo** [Sinytra/ForgifiedFabricAPI#185]
Hey,

FFAPI is incompatible with modern forwarding on NeoForge as mentioned in

-> https://github.com/adde0109/Proxy-Compatible-Forge/issues/40
-> https://github.com/Sonic2423/NeoForwarding/issues/12

Hopeing for this to get fixed.

Kind regards,
Collin

**Comment by MRMDevStudios** [comment]
bump

**Comment by windy664** [comment]
+ 1

**Comment by windy664** [comment]
After research, it also was found that it cannot be used for WaterFall

io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 57 out of bounds for length 54
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:101) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 57 out of bounds for length 54
        at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:884) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:306) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:83) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:534) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91) ~[waterfall-1.21-582.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
        ... 24 more

**Comment by P5ina** [comment]
Is there any workaround for now?

**Comment by Su5eD** [comment]
Reproduced the issue with NeoForge only (FFAPI NOT installed on either client or server)

<img width="1308" alt="Image" src="https://github.com/user-attachments/assets/cd87bd41-84b4-464a-9c2e-a020faea123d" />

**Comment by MRMDevStudios** [comment]
Read me and this may actually be a both sided issue not just the forwarding @Su5eD 

https://github.com/Gabwasnt/NeoVelocity/issues/10#issuecomment-2765846807
