### ISSUE TITLE
Conflict with other mods

### ISSUE THREAD

**Issue by lockf** [Sinytra/ForgifiedFabricAPI#23]
### Describe the bug

This mod seems to have conflict with other mods

### Steps to reproduce

1. install  easy mob farm (https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm) or open parties and claims (https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)

### Additional context

Exception in thread "main" java.lang.module.ResolutionException: Modules creativecore and net.fabricmc.loader export package net.fabricmc.api to module **openpartiesandclaims**

at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)

at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)

at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)

at java.base/java.lang.module.Resolver.finish(Resolver.java:380)

at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)

at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

**Comment by lockf** [comment]
I'm not sure if it can be fixed, but at least I can give a heads up

- lockf

**Comment by Su5eD** [comment]
Same issue as #22
